import { expect, test, type Page } from '@playwright/test'
const base = '/api/v1/admin/academic/'
async function open(page: Page, link: string) {
 await page.getByRole('navigation', { name: 'Quản trị học vụ' }).getByRole('link', { name: link, exact: true }).click()
}
async function save(page: Page, resource: string, method: string) {
 const response = page.waitForResponse((response) => new URL(response.url()).pathname.startsWith(base + resource) && response.request().method() === method)
 await page.getByRole('dialog').getByRole('button', { name: 'Lưu', exact: true }).click()
 return response
}
async function select(page: Page, label: string, option: string) {
 await page.getByRole('dialog').getByRole('combobox', { name: label, exact: true }).click()
 await page.getByTitle(option, { exact: true }).click()
 if (label === 'Đơn vị') await expect(page.getByRole('dialog').getByTitle(option, { exact: true })).toBeVisible()
}
test('real Academic catalog and delivery enforce faculty/capacity and preserve restored membership', async ({ page }) => {
 test.setTimeout(120_000)
 await page.goto('/')
 await page.getByLabel('Email', { exact: true }).fill('browser-admin@example.test')
 await page.getByLabel('Mật khẩu', { exact: true }).fill(process.env.CAMPUS_TEST_PASSWORD!)
 await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
 await expect(page.getByRole('banner').getByText('browser-admin@example.test')).toBeVisible()
 await page.evaluate(async () => {
  const token = await navigator.locks.request('campus-auth-cookie', async () => (await fetch('/api/v1/auth/refresh', { method: 'POST', credentials: 'include' })).json())
  const post = async (path: string, body: unknown) => {
   const response = await fetch('/api/v1/admin/' + path, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + token.accessToken }, body: JSON.stringify(body) })
   if (response.status !== 201) throw new Error('Fixture create failed: ' + response.status)
   return response.json()
  }
  const unit = await post('organization-units', { code: 'ACAUI', name: 'Khoa học vụ UI', unitType: 'FACULTY', status: 'ACTIVE' })
  await post('faculty-staff', { personnelNumber: 'ACAGV', fullName: 'Giảng viên học vụ', personnelType: 'FACULTY', status: 'ACTIVE', organizationUnitId: unit.id })
  for (const code of ['ACASV1', 'ACASV2']) await post('students', { studentNumber: code, fullName: 'Sinh viên ' + code, status: 'ACTIVE', organizationUnitId: unit.id })
 })
 await page.goto('/admin/academic/programs')
 await page.getByRole('button', { name: 'Thêm chương trình', exact: true }).click()
 await page.getByRole('dialog').getByLabel('Mã', { exact: true }).fill('ACAP')
 await page.getByRole('dialog').getByLabel('Tên chương trình', { exact: true }).fill('Chương trình UI')
 await select(page, 'Đơn vị', 'ACAUI · Khoa học vụ UI')
 const programResponse = await save(page, 'programs', 'POST')
 expect(programResponse.status()).toBe(201)
 const program = await programResponse.json()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 
 await page.getByRole('row').filter({ hasText: 'ACAP' }).getByRole('button', { name: 'Xem / sửa' }).click()
 await expect(page.getByRole('dialog').getByLabel('Tên chương trình')).toHaveValue('Chương trình UI')
 const changed = await page.evaluate(async (record) => {
  const tokens = await navigator.locks.request('campus-auth-cookie', async () => (await fetch('/api/v1/auth/refresh', { method: 'POST', credentials: 'include' })).json())
  return (await fetch('/api/v1/admin/academic/programs/' + record.id, { method: 'PUT', credentials: 'include', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + tokens.accessToken }, body: JSON.stringify({ code: record.code, name: 'Chương trình phiên khác', organizationUnitId: record.organizationUnitId, status: record.status, expectedVersion: record.rowVersion }) })).status
 }, program)
 expect(changed).toBe(200)
 await page.getByRole('dialog').getByLabel('Tên chương trình').fill('Chương trình bản cũ')
 expect((await save(page, 'programs', 'PUT')).status()).toBe(409)
 await expect(page.getByRole('dialog').getByRole('button', { name: 'Lưu', exact: true })).toBeDisabled()
 await page.getByRole('dialog').getByRole('button', { name: 'Tải lại', exact: true }).click()
 const confirm = page.getByRole('dialog').filter({ hasText: 'Tải lại dữ liệu mới?' })
 await confirm.getByRole('button', { name: 'Tải lại', exact: true }).click()
 await expect(confirm).not.toBeVisible()
 await expect(page.getByRole('dialog').getByLabel('Tên chương trình')).toHaveValue('Chương trình phiên khác')
 await page.getByRole('dialog').getByLabel('Tên chương trình').fill('Chương trình cập nhật')
 expect((await save(page, 'programs', 'PUT')).status()).toBe(200)
 await expect(page.getByRole('dialog')).not.toBeVisible()

 await open(page, 'Môn học')
 await page.getByRole('button', { name: 'Thêm môn học', exact: true }).click()
 await page.getByRole('dialog').getByLabel('Mã', { exact: true }).fill('ACA101')
 await page.getByRole('dialog').getByLabel('Tên môn học', { exact: true }).fill('Môn học UI')
 await page.getByRole('dialog').getByRole('spinbutton', { name: 'Số tín chỉ', exact: true }).fill('3')
 await select(page, 'Đơn vị', 'ACAUI · Khoa học vụ UI')
 expect((await save(page, 'courses', 'POST')).status()).toBe(201)
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await open(page, 'Học kỳ')
 await page.getByRole('button', { name: 'Thêm học kỳ', exact: true }).click()
 let dialog = page.getByRole('dialog')
 await dialog.getByLabel('Mã', { exact: true }).fill('ACA2026')
 await dialog.getByLabel('Tên học kỳ', { exact: true }).fill('Học kỳ UI')
 await dialog.getByLabel('Ngày bắt đầu').fill('2026-10-01')
 await dialog.getByLabel('Ngày kết thúc').fill('2026-12-31')
 expect((await save(page, 'terms', 'POST')).status()).toBe(201)
 await expect(dialog).not.toBeVisible()
 await page.getByRole('row').filter({ hasText: 'ACA2026' }).getByRole('button', { name: 'Xem / sửa' }).click()
 await select(page, 'Trạng thái', 'ACTIVE')
 expect((await save(page, 'terms', 'PUT')).status()).toBe(200)
 await expect(dialog).not.toBeVisible()
 await open(page, 'Đợt mở môn')
 await page.getByRole('button', { name: 'Thêm đợt mở môn', exact: true }).click()
 await select(page, 'Học kỳ', 'ACA2026 · Học kỳ UI')
 await select(page, 'Môn học', 'ACA101 · Môn học UI')
 const offering = await (await save(page, 'offerings', 'POST')).json()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('row').filter({ hasText: offering.id }).getByRole('button', { name: 'Xem / sửa' }).click()
 await select(page, 'Trạng thái', 'OPEN')
 expect((await save(page, 'offerings', 'PUT')).status()).toBe(200)
 await expect(dialog).not.toBeVisible()
 await open(page, 'Lớp học phần')
 await page.getByRole('button', { name: 'Thêm lớp học phần', exact: true }).click()
 dialog = page.getByRole('dialog')
 await select(page, 'Đợt mở môn', offering.id + ' · OPEN')
 await dialog.getByLabel('Mã', { exact: true }).fill('ACASEC')
 await dialog.getByRole('spinbutton', { name: 'Sức chứa', exact: true }).fill('1')
 expect((await save(page, 'sections', 'POST')).status()).toBe(201)
 await expect(dialog).not.toBeVisible()
 await page.getByRole('row').filter({ hasText: 'ACASEC' }).getByRole('button', { name: 'Xem / sửa' }).click()
 await select(page, 'Trạng thái', 'OPEN')
 const missingFaculty = await save(page, 'sections', 'PUT')
 expect(missingFaculty.status()).toBe(409)
 await expect(dialog.getByText('Mã lỗi: ACADEMIC_REFERENCE_UNAVAILABLE')).toBeVisible()
 await select(page, 'Giảng viên', 'ACAGV · Giảng viên học vụ')
 expect((await save(page, 'sections', 'PUT')).status()).toBe(200)
 await expect(dialog).not.toBeVisible()
 await page.getByRole('row').filter({ hasText: 'ACASEC' }).getByRole('button', { name: 'Xem / sửa' }).click()
 await expect(dialog.getByLabel('Mã', { exact: true })).toBeDisabled()
 await expect(dialog.getByRole('spinbutton', { name: 'Sức chứa', exact: true })).toBeDisabled()
 await dialog.getByRole('button', { name: 'Hủy', exact: true }).click()
 await open(page, 'Ghi danh')
 await page.getByRole('button', { name: 'Thêm ghi danh', exact: true }).click()
 await select(page, 'Sinh viên', 'ACASV1 · Sinh viên ACASV1')
 await select(page, 'Lớp học phần', 'ACASEC · OPEN')
 const member = await (await save(page, 'enrollments', 'POST')).json()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('button', { name: 'Thêm ghi danh', exact: true }).click()
 await select(page, 'Sinh viên', 'ACASV2 · Sinh viên ACASV2')
 await select(page, 'Lớp học phần', 'ACASEC · OPEN')
 expect((await save(page, 'enrollments', 'POST')).status()).toBe(409)
 await expect(dialog.getByText('Mã lỗi: SECTION_CAPACITY_EXCEEDED')).toBeVisible()
 await dialog.getByRole('button', { name: 'Hủy', exact: true }).click()
 await page.getByRole('row').filter({ hasText: 'ACASV1' }).getByRole('button', { name: 'Xem / sửa' }).click()
 await select(page, 'Trạng thái', 'WITHDRAWN')
 const withdrawn = await (await save(page, 'enrollments', 'PUT')).json()
 expect(withdrawn.id).toBe(member.id)
 expect(withdrawn.status).toBe('WITHDRAWN')
 await expect(dialog).not.toBeVisible()
 await page.getByRole('row').filter({ hasText: 'ACASV1' }).getByRole('button', { name: 'Xem / sửa' }).click()
 await select(page, 'Trạng thái', 'ENROLLED')
 const restored = await (await save(page, 'enrollments', 'PUT')).json()
 expect(restored.id).toBe(member.id)
 expect(restored.status).toBe('ENROLLED')
 expect(restored.rowVersion).toBeGreaterThan(withdrawn.rowVersion)
 await expect(dialog).not.toBeVisible()
 await expect(page.getByRole('row').filter({ hasText: 'ACASV1' })).toContainText('ENROLLED')
})
