import { test, expect } from '@playwright/test'
test('real Notification preserves snapshots, rejects stale publication and retains immutable publication', async ({ page }) => {
 test.setTimeout(90000)
 await page.goto('/')
 await page.getByLabel('Email', { exact: true }).fill('browser-admin@example.test')
 await page.getByLabel('Mật khẩu', { exact: true }).fill(process.env.CAMPUS_TEST_PASSWORD!)
 await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
 await expect(page.getByRole('banner').getByText('browser-admin@example.test')).toBeVisible()
 await page.goto('/admin/notifications/templates')
 await page.getByRole('button', { name: 'Thêm mẫu thông báo', exact: true }).click()
 const dialog = page.getByRole('dialog')
 await dialog.getByLabel('Mã mẫu', { exact: true }).fill('NOTUI')
 await dialog.getByLabel('Tên mẫu', { exact: true }).fill('Mẫu UI')
 await dialog.getByLabel('Tiêu đề', { exact: true }).fill('Thông báo UI')
 await dialog.getByLabel('Nội dung', { exact: true }).fill('<script>văn bản thuần</script>\nDòng thứ hai')
 await dialog.getByRole('button', { name: 'Lưu', exact: true }).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('navigation', { name: 'Quản trị thông báo' }).getByRole('link', { name: 'Thông báo', exact: true }).click()
 await expect(page.getByRole('heading', { name: 'Thông báo', exact: true })).toBeVisible()
 await page.getByRole('button', { name: 'Thêm thông báo', exact: true }).click()
 await dialog.getByRole('combobox', { name: 'Mẫu thông báo', exact: true }).click()
 await page.getByTitle('NOTUI · Mẫu UI', { exact: true }).click()
 const createdResponse = page.waitForResponse((response) => new URL(response.url()).pathname === '/api/v1/admin/notifications/notices' && response.request().method() === 'POST')
 await dialog.getByRole('button', { name: 'Lưu', exact: true }).click()
 const notice = await (await createdResponse).json()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('navigation', { name: 'Quản trị thông báo' }).getByRole('link', { name: 'Mẫu thông báo', exact: true }).click()
 await expect(page.getByRole('heading', { name: 'Mẫu thông báo', exact: true })).toBeVisible()
 await page.getByRole('row').filter({ hasText: 'NOTUI' }).getByRole('button', { name: 'Xem / sửa', exact: true }).click()
 await expect(dialog.getByLabel('Tiêu đề', { exact: true })).toHaveValue('Thông báo UI')
 await dialog.getByLabel('Tiêu đề', { exact: true }).fill('Tiêu đề mẫu mới')
 await dialog.getByLabel('Nội dung', { exact: true }).fill('Nội dung mẫu mới')
 await dialog.getByRole('button', { name: 'Lưu', exact: true }).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('navigation', { name: 'Quản trị thông báo' }).getByRole('link', { name: 'Thông báo', exact: true }).click()
 await expect(page.getByRole('heading', { name: 'Thông báo', exact: true })).toBeVisible()
 await expect(page.getByRole('row').filter({ hasText: 'Thông báo UI' })).toBeVisible()
 await page.getByRole('row').filter({ hasText: 'Thông báo UI' }).getByRole('button', { name: 'Phát hành', exact: true }).click()
 await expect(dialog.getByText('<script>văn bản thuần</script>\nDòng thứ hai', { exact: true })).toBeVisible()
 await dialog.getByRole('combobox', { name: 'Tài khoản nhận', exact: true }).click()
 await page.getByTitle('browser-user@example.test · Browser test account', { exact: true }).click()
 await dialog.getByRole('button', { name: 'Thêm người nhận', exact: true }).click()
 const updatedStatus = await page.evaluate(async (record) => {
  const tokens = await navigator.locks.request('campus-auth-cookie', async () => (await fetch('/api/v1/auth/refresh', { method: 'POST', credentials: 'include' })).json())
  const response = await fetch('/api/v1/admin/notifications/notices/' + record.id, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + tokens.accessToken }, body: JSON.stringify({ title: 'Thông báo phiên mới', body: 'Nội dung đã chỉnh', expectedVersion: record.rowVersion }) })
  return response.status
 }, notice)
 expect(updatedStatus).toBe(200)
 await dialog.getByRole('button', { name: 'Xác nhận phát hành', exact: true }).click()
 await expect(dialog.getByText('Mã lỗi: CONCURRENT_MODIFICATION')).toBeVisible()
 await expect(dialog.getByRole('button', { name: 'Xác nhận phát hành', exact: true })).toBeDisabled()
 await dialog.getByRole('button', { name: 'Đóng biểu mẫu', exact: true }).click()
 await page.reload()
 await page.getByRole('row').filter({ hasText: 'Thông báo phiên mới' }).getByRole('button', { name: 'Phát hành', exact: true }).click()
 await expect(dialog.getByText('Nội dung đã chỉnh', { exact: true })).toBeVisible()
 await dialog.getByRole('combobox', { name: 'Tài khoản nhận', exact: true }).click()
 await page.getByTitle('browser-user@example.test · Browser test account', { exact: true }).click()
 await dialog.getByRole('button', { name: 'Thêm người nhận', exact: true }).click()
 const publishedResponse = page.waitForResponse((response) => response.url().includes('/notices/' + notice.id + '/publish') && response.request().method() === 'POST')
 await dialog.getByRole('button', { name: 'Xác nhận phát hành', exact: true }).click()
 expect((await publishedResponse).status()).toBe(200)
 await expect(dialog).not.toBeVisible()
 const row = page.getByRole('row').filter({ hasText: 'Thông báo phiên mới' })
 await expect(row).toContainText('PUBLISHED')
 await expect(row.getByRole('button', { name: 'Phát hành', exact: true })).toBeDisabled()
 await row.getByRole('button', { name: 'Xem / sửa', exact: true }).click()
 await expect(dialog.getByLabel('Nội dung', { exact: true })).toHaveValue('Nội dung đã chỉnh')
 await expect(dialog.getByLabel('Nội dung', { exact: true })).toBeDisabled()
 await expect(dialog.getByRole('button', { name: 'Lưu', exact: true })).toHaveCount(0)
})
