import { test, expect } from '@playwright/test'

test('real ADMIN creates account, changes roles/status, resets password and cannot mutate self', async ({ page }) => {
 test.setTimeout(60_000)
 await page.goto('/')
 await page.getByLabel('Email', { exact: true }).fill('browser-admin@example.test')
 await page.getByLabel('Mật khẩu', { exact: true }).fill(process.env.CAMPUS_TEST_PASSWORD!)
 await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
 await expect(page.getByRole('banner').getByText('browser-admin@example.test')).toBeVisible()
 await page.goto('/admin/users')
 const own = page.getByRole('row').filter({ hasText: 'browser-admin@example.test' })
 await expect(own.getByRole('button', { name: 'Đổi quyền', exact: true })).toBeDisabled()
 await expect(own.getByRole('button', { name: 'Đổi trạng thái', exact: true })).toBeDisabled()
 await expect(own.getByRole('button', { name: 'Đặt lại mật khẩu', exact: true })).toBeDisabled()
 await page.getByRole('button', { name: 'Thêm tài khoản', exact: true }).click()
 let dialog = page.getByRole('dialog')
 await dialog.getByLabel('Email', { exact: true }).fill('ui-managed@example.test')
 await dialog.getByLabel('Tên hiển thị', { exact: true }).fill('Tài khoản kiểm thử UI')
 await dialog.getByLabel('Mật khẩu ban đầu', { exact: true }).fill(process.env.CAMPUS_TEST_PASSWORD!)
 await dialog.getByRole('button', { name: 'Lưu', exact: true }).click()
 await expect(dialog).not.toBeVisible()
 let row = page.getByRole('row').filter({ hasText: 'ui-managed@example.test' })
 await expect(row).toContainText('Tài khoản kiểm thử UI')
 await row.getByRole('button', { name: 'Đổi quyền', exact: true }).click()
 dialog = page.getByRole('dialog')
 await dialog.getByLabel('Quyền mới', { exact: true }).click()
 await page.getByTitle('ADMIN', { exact: true }).click()
 await page.keyboard.press('Escape')
 await dialog.getByRole('button', { name: 'Lưu', exact: true }).click()
 await expect(dialog).not.toBeVisible()
 row = page.getByRole('row').filter({ hasText: 'ui-managed@example.test' })
 await expect(row).toContainText('ADMIN')
 await row.getByRole('button', { name: 'Đổi trạng thái', exact: true }).click()
 dialog = page.getByRole('dialog')
 await dialog.getByLabel('Trạng thái mới', { exact: true }).click()
 await page.getByTitle('SUSPENDED', { exact: true }).click()
 await dialog.getByRole('button', { name: 'Lưu', exact: true }).click()
 await expect(dialog).not.toBeVisible()
 await expect(row).toContainText('SUSPENDED')
 await row.getByRole('button', { name: 'Đặt lại mật khẩu', exact: true }).click()
 dialog = page.getByRole('dialog')
 await dialog.getByLabel('Mật khẩu mới', { exact: true }).fill(process.env.CAMPUS_TEST_PASSWORD! + 'x')
 const reset = page.waitForResponse((response) => response.url().endsWith('/password-reset') && response.request().method() === 'POST')
 await dialog.getByRole('button', { name: 'Lưu', exact: true }).click()
 expect((await reset).status()).toBe(204)
 await expect(dialog).not.toBeVisible()
 await row.getByRole('button', { name: 'Chi tiết', exact: true }).click()
 await expect(page.getByRole('dialog')).toContainText('SUSPENDED')
 await expect(page.getByRole('dialog')).toContainText('ADMIN')
 await page.getByRole('dialog').getByRole('button', { name: 'Đóng biểu mẫu', exact: true }).click()
 await page.getByRole('button', { name: 'Thêm tài khoản', exact: true }).click()
 dialog = page.getByRole('dialog')
 await dialog.getByLabel('Email', { exact: true }).fill('ui-managed@example.test')
 await dialog.getByLabel('Tên hiển thị', { exact: true }).fill('Trùng email')
 await dialog.getByLabel('Mật khẩu ban đầu', { exact: true }).fill(process.env.CAMPUS_TEST_PASSWORD!)
 await dialog.getByRole('button', { name: 'Lưu', exact: true }).click()
 await expect(dialog.getByText('Mã lỗi: EMAIL_ALREADY_EXISTS')).toBeVisible()
 await expect(dialog.getByLabel('Email', { exact: true })).toHaveValue('ui-managed@example.test')

})
